export const SIGNAL_PROTOCOL_VERSION = 1 as const;

export const DEFAULT_SIGNAL_TTL_SECONDS = 600;
export const MIN_SIGNAL_TTL_SECONDS = 60;
export const MAX_SIGNAL_TTL_SECONDS = 3_600;

export const SIGNAL_BIND_DEADLINE_MS = 5_000;
export const MAX_SIGNAL_FRAME_BYTES = 65_536;
export const MAX_SIGNAL_SDP_BYTES = 60 * 1_024;
export const MAX_SIGNAL_CANDIDATE_BYTES = 4_096;
export const MAX_SIGNAL_CANDIDATES_PER_PEER = 16;
export const MAX_SIGNAL_FORWARDED_BYTES = 1_048_576;

export const SIGNAL_LISTENER_SECRET_BYTES = 32;
export const SIGNAL_LISTENER_SECRET_LENGTH = 43;

export const SIGNAL_POLICY_CLOSE_CODE = 1008;
export const SIGNAL_EXPIRED_CLOSE_CODE = 1001;
export const SIGNAL_INTERNAL_CLOSE_CODE = 1011;
