#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

rm -rf dist
npx tsc --project tsconfig.build.json

# worker-configuration.d.ts (generated by `wrangler types`) declares ambient
# globals — CloudflareBindings, D1Database, ExecutionContext, etc. — that
# the emitted declarations reference by name but never import. Without it
# alongside dist/client.d.ts, an external consumer's `AppType` reference
# fails to resolve those names (verified: `Cannot find name 'CloudflareBindings'`
# in a from-scratch consumer with only `hono` installed).
cp worker-configuration.d.ts dist/worker-configuration.d.ts
printf '/// <reference path="./worker-configuration.d.ts" />\n%s\n' \
  "$(cat dist/client.d.ts)" > dist/client.d.ts
